title: Ariel "Ari" Lorenzo # your name (or website title) here
logo: "/images/ari-rwb-cassette-tape.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a full-stack developer with about 3 years of experience in the field. I have worked mostly with educational institutes and collaborations with other developers and designers.
  <br><br>
  I try my best to keep track of the changing trends in web and mobile development to always stay current.
  <br><br>
  <a href="https://www.linkedin.com/in/fausto-a-lorenzo-b88270114/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
